Perfect — keep that certs: structure, and we’ll enforce your naming standard automatically from qm.name + env.

Naming standard you asked for

Given:

qm.name: <qmgr>

env: <env>

We generate:

QMGR certificate name: <qmgr>-<env>-certificate

QMGR secret name: <qmgr>-<env>-tls

CRR certificate name: <qmgr>-<env>-crr-certificate

CRR secret name: <qmgr>-<env>-crr-tls

You can still override name / secretName explicitly if you want, but by default it uses the standard above.




1) Values structure (values.yaml) in your preferred format

qm:
  name: qmgr

env: dev  # dev|test|prod

certs:
  enabled: true

  qmgr:
    create: true

    # If you leave name/secretName empty or omit them:
    # name      => <qm.name>-<env>-certificate
    # secretName=> <qm.name>-<env>-tls
    name: ""        # optional override
    secretName: ""  # optional override

    commonName: ""
    dnsNames:
      - "f-dev-adm2e-svrconn."
      - "qmgr-dev-app2e-svrconn."
      - "qmgr-ibm-mq-0"
      - "qmgr-ibm-mq-1"
      - "qmgr-ibm-mq-2"

    renewBefore: "24h"
    duration: "17520h"

    privateKey:
      rotationPolicy: Always
      algorithm: RSA
      size: 2048

    subject:
      organizations: ["your-org"]
      countries: ["US"]
      organizationalUnits: [""]
      provinces: [""]
      localities: [""]

    issuerRef:
      name: "venafi-fpp-cluster-issuer"
      kind: "ClusterIssuer"
      group: "cert-manager.io"

  crr:
    create: true

    # If blank/omitted:
    # name      => <qm.name>-<env>-crr-certificate
    # secretName=> <qm.name>-<env>-crr-tls
    name: ""        # optional override
    secretName: ""  # optional override

    commonName: "qmgr-dev-crr."
    dnsNames:
      - "qmgr-dev-crr."
      - "qmgr-ibm-mq-0"
      - "qmgr-ibm-mq-1"
      - "qmgr-ibm-mq-2"

    renewBefore: "24h"
    duration: "170h"

    privateKey:
      rotationPolicy: Always
      algorithm: RSA
      size: 2048

    # crr can have its own subject too (optional)
    subject:
      organizations: ["your-org"]
      countries: ["US"]
      organizationalUnits: ["mq"]
      provinces: [""]
      localities: [""]

    issuerRef:
      name: "venafi-fpp-cluster-issuer"
      kind: "ClusterIssuer"
      group: "cert-manager.io"



2) helpers: build names from qm.name + env (and allow overrides)

Put this into templates/_helpers.tpl:



{{- define "mq.qmName" -}}
{{- required "qm.name is required" .Values.qm.name | lower | trunc 40 | trimSuffix "-" -}}
{{- end -}}

{{- define "mq.env" -}}
{{- default "dev" .Values.env | lower -}}
{{- end -}}

{{- define "mq.certs.qmgr.name" -}}
{{- $override := default "" .Values.certs.qmgr.name -}}
{{- if $override -}}
{{- $override | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s-certificate" (include "mq.qmName" .) (include "mq.env" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}

{{- define "mq.certs.qmgr.secretName" -}}
{{- $override := default "" .Values.certs.qmgr.secretName -}}
{{- if $override -}}
{{- $override | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s-tls" (include "mq.qmName" .) (include "mq.env" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}

{{- define "mq.certs.crr.name" -}}
{{- $override := default "" .Values.certs.crr.name -}}
{{- if $override -}}
{{- $override | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s-crr-certificate" (include "mq.qmName" .) (include "mq.env" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}

{{- define "mq.certs.crr.secretName" -}}
{{- $override := default "" .Values.certs.crr.secretName -}}
{{- if $override -}}
{{- $override | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s-crr-tls" (include "mq.qmName" .) (include "mq.env" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}



3) Template: templates/certificates.yaml (creates QMGR + CRR Certificates)

{{- if and .Values.certs.enabled .Values.certs.qmgr.create }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "mq.certs.qmgr.name" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  secretName: {{ include "mq.certs.qmgr.secretName" . | quote }}
  {{- with .Values.certs.qmgr.renewBefore }}
  renewBefore: {{ . | quote }}
  {{- end }}
  {{- with .Values.certs.qmgr.duration }}
  duration: {{ . | quote }}
  {{- end }}

  {{- with .Values.certs.qmgr.commonName }}
  commonName: {{ . | quote }}
  {{- end }}

  {{- with .Values.certs.qmgr.dnsNames }}
  dnsNames:
  {{- range . }}
    - {{ . | quote }}
  {{- end }}
  {{- end }}

  {{- with .Values.certs.qmgr.privateKey }}
  privateKey:
    {{- with .rotationPolicy }}rotationPolicy: {{ . | quote }}{{- end }}
    {{- with .algorithm }}algorithm: {{ . | quote }}{{- end }}
    {{- with .size }}size: {{ . }}{{- end }}
  {{- end }}

  {{- with .Values.certs.qmgr.subject }}
  subject:
    {{- with .organizations }}
    organizations:
{{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .countries }}
    countries:
{{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .organizationalUnits }}
    organizationalUnits:
{{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .provinces }}
    provinces:
{{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .localities }}
    localities:
{{ toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}

  issuerRef:
    name: {{ .Values.certs.qmgr.issuerRef.name | quote }}
    kind: {{ .Values.certs.qmgr.issuerRef.kind | quote }}
    {{- with .Values.certs.qmgr.issuerRef.group }}
    group: {{ . | quote }}
    {{- end }}
{{- end }}

{{- if and .Values.certs.enabled .Values.certs.crr.create }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "mq.certs.crr.name" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  secretName: {{ include "mq.certs.crr.secretName" . | quote }}
  {{- with .Values.certs.crr.renewBefore }}
  renewBefore: {{ . | quote }}
  {{- end }}
  {{- with .Values.certs.crr.duration }}
  duration: {{ . | quote }}
  {{- end }}

  {{- with .Values.certs.crr.commonName }}
  commonName: {{ . | quote }}
  {{- end }}

  {{- with .Values.certs.crr.dnsNames }}
  dnsNames:
  {{- range . }}
    - {{ . | quote }}
  {{- end }}
  {{- end }}

  {{- with .Values.certs.crr.privateKey }}
  privateKey:
    {{- with .rotationPolicy }}rotationPolicy: {{ . | quote }}{{- end }}
    {{- with .algorithm }}algorithm: {{ . | quote }}{{- end }}
    {{- with .size }}size: {{ . }}{{- end }}
  {{- end }}

  {{- with .Values.certs.crr.subject }}
  subject:
    {{- with .organizations }}
    organizations:
{{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .countries }}
    countries:
{{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .organizationalUnits }}
    organizationalUnits:
{{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .provinces }}
    provinces:
{{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .localities }}
    localities:
{{ toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}

  issuerRef:
    name: {{ .Values.certs.crr.issuerRef.name | quote }}
    kind: {{ .Values.certs.crr.issuerRef.kind | quote }}
    {{- with .Values.certs.crr.issuerRef.group }}
    group: {{ . | quote }}
    {{- end }}
{{- end }}



4) Where to use these secret names in QueueManager (one-liners)

Replication TLS secret (CRR):

tls:
  secretName: {{ include "mq.certs.crr.secretName" . | quote }}



PKI key store secret (QMGR / channel):


pki:
  keys:
    - name: {{ .Values.pki.keyName | quote }}
      secret:
        secretName: {{ include "mq.certs.qmgr.secretName" . | quote }}
        items:
{{- toYaml .Values.pki.items | nindent 10 }}







{{- if and .Values.certs.enabled .Values.certs.qmgr.create }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "mq.certs.qmgr.name" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  secretName: {{ include "mq.certs.qmgr.secretName" . | quote }}

  {{- with .Values.certs.qmgr.duration }}
  duration: {{ . | quote }}
  {{- end }}

  {{- with .Values.certs.qmgr.renewBefore }}
  renewBefore: {{ . | quote }}
  {{- end }}

  {{- with .Values.certs.qmgr.commonName }}
  commonName: {{ . | quote }}
  {{- end }}

  {{- with .Values.certs.qmgr.dnsNames }}
  dnsNames:
{{ toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.certs.qmgr.privateKey }}
  privateKey:
{{ toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.certs.qmgr.subject }}
  subject:
{{ toYaml . | nindent 4 }}
  {{- end }}

  issuerRef:
{{ toYaml .Values.certs.qmgr.issuerRef | nindent 4 }}
{{- end }}




{{- if and .Values.certs.enabled .Values.certs.crr.create }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "mq.certs.crr.name" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  secretName: {{ include "mq.certs.crr.secretName" . | quote }}

  {{- with .Values.certs.crr.duration }}
  duration: {{ . | quote }}
  {{- end }}

  {{- with .Values.certs.crr.renewBefore }}
  renewBefore: {{ . | quote }}
  {{- end }}

  {{- with .Values.certs.crr.commonName }}
  commonName: {{ . | quote }}
  {{- end }}

  {{- with .Values.certs.crr.dnsNames }}
  dnsNames:
{{ toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.certs.crr.privateKey }}
  privateKey:
{{ toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.certs.crr.subject }}
  subject:
{{ toYaml . | nindent 4 }}
  {{- end }}

  issuerRef:
{{ toYaml .Values.certs.crr.issuerRef | nindent 4 }}
{{- end }}




================================================================================
IBM MQ Native HA / CRR – Operations Notes
================================================================================

This chart deploys an IBM MQ QueueManager using the IBM MQ Operator on
OpenShift. It may include:
- Native HA or Native HA + CRR
- MQSC and mq.ini configuration via ConfigMaps
- LDAP configuration via Secret
- TLS certificates via cert-manager
- OpenShift Routes for external MQ access

--------------------------------------------------------------------------------
1) Helm – Common Commands
--------------------------------------------------------------------------------

Check Helm version:
  helm version

Render templates locally (NO deployment):
  helm template mq-nativeha-crr ./mq-nativeha-crr-helm \
    -n <namespace> \
    -f values.yaml

Render with debug (recommended):
  helm template mq-nativeha-crr ./mq-nativeha-crr-helm \
    -n <namespace> \
    -f values.yaml \
    --debug

Install new release:
  helm install mq-nativeha-crr ./mq-nativeha-crr-helm \
    -n <namespace> \
    -f values.yaml

Upgrade existing release:
  helm upgrade mq-nativeha-crr ./mq-nativeha-crr-helm \
    -n <namespace> \
    -f values.yaml

Install or upgrade (most common):
  helm upgrade --install mq-nativeha-crr ./mq-nativeha-crr-helm \
    -n <namespace> \
    -f values.yaml

Install with environment overlays:
  helm upgrade --install mq-nativeha-crr ./mq-nativeha-crr-helm \
    -n <namespace> \
    -f values.yaml \
    -f values-live.yaml

Dry-run (validate without applying):
  helm upgrade --install mq-nativeha-crr ./mq-nativeha-crr-helm \
    -n <namespace> \
    -f values.yaml \
    --dry-run

List releases:
  helm list -n <namespace>

Check release status:
  helm status mq-nativeha-crr -n <namespace>

Uninstall release:
  helm uninstall mq-nativeha-crr -n <namespace>

--------------------------------------------------------------------------------
2) OpenShift (oc) – Common Commands
--------------------------------------------------------------------------------

Login:
  oc login <cluster-url>

Switch namespace:
  oc project <namespace>

List QueueManagers:
  oc get qmgr

Describe QueueManager (IMPORTANT):
  oc describe qmgr <qmgr-name>

List MQ pods:
  oc get pods

Pod details:
  oc describe pod <pod-name>

View MQ logs:
  oc logs <pod-name>

Follow logs:
  oc logs -f <pod-name>

Exec into MQ pod:
  oc exec -it <pod-name> -- bash

--------------------------------------------------------------------------------
3) MQ Runtime Checks
--------------------------------------------------------------------------------

Check Native HA / CRR status:
  oc exec -it <active-pod> -- dspmq -o nativeha -g

Expected:
  ROLE(Active)
  QUORUM(3/3)
  INSYNC(yes)

Check QM status:
  oc exec -it <pod-name> -- dspmq

--------------------------------------------------------------------------------
4) ConfigMaps and Secrets
--------------------------------------------------------------------------------

List ConfigMaps:
  oc get configmap

View MQSC / INI ConfigMap:
  oc get configmap <name> -o yaml

List Secrets:
  oc get secret

Describe TLS secret:
  oc describe secret <secret-name>

--------------------------------------------------------------------------------
5) Routes (External MQ Access)
--------------------------------------------------------------------------------

List Routes:
  oc get route

Describe Route:
  oc describe route <route-name>

MQ Routes use:
- TLS passthrough
- SNI-based routing
- Port 1414

--------------------------------------------------------------------------------
6) Certificates (cert-manager)
--------------------------------------------------------------------------------

List Certificates:
  oc get certificate

Describe Certificate:
  oc describe certificate <certificate-name>

Check TLS Secret:
  oc get secret <tls-secret-name> -o yaml

--------------------------------------------------------------------------------
7) Troubleshooting
--------------------------------------------------------------------------------

Recent events:
  oc get events --sort-by=.metadata.creationTimestamp

MQ Operator logs:
  oc logs -n ibm-mq <mq-operator-pod>

Validate rendered YAML:
  helm template mq-nativeha-crr ./mq-nativeha-crr-helm \
    -f values.yaml | oc apply --dry-run=client -f -

--------------------------------------------------------------------------------
8) Recommended Ops Flow
--------------------------------------------------------------------------------

1) Render templates:
   helm template ... --debug

2) Dry-run install:
   helm upgrade --install ... --dry-run

3) Deploy:
   helm upgrade --install ...

4) Verify:
   oc get qmgr
   oc get pods

5) Check HA status:
   oc exec -it <pod> -- dspmq -o nativeha -g

--------------------------------------------------------------------------------
END OF NOTES
--------------------------------------------------------------------------------











import pymqi
from pymqi import CMQC

QMGR_NAME   = "QM1"
CHANNEL     = "APP.SVRCONN"
HOST        = "mq-route.apps.example.com"   # OCP Route host (or service DNS)
PORT        = "443"                         # often 443 for Route passthrough; or 1414 if ClusterIP/LoadBalancer
CONNAME     = f"{HOST}({PORT})"

USER        = "myldapuser"
PASSWORD    = "myldappassword"

# --- TLS settings ---
# For KDB repositories, use the file path WITHOUT the .kdb extension.
# Example files:
#   /certs/app-trust.kdb
#   /certs/app-trust.sth   (stash file)  OR you can provide password via env MQSSLKEYR/MQSSLKEYTPWD in some setups
KEY_REPO    = "/certs/app-trust"          # truststore that contains CA + QMGR signer chain
CIPHERSPEC  = "TLS_RSA_WITH_AES_256_CBC_SHA256"  # must match SVRCONN SSLCIPH

def connect():
    # Client channel definition
    cd = pymqi.CD()
    cd.ChannelName = CHANNEL.encode()
    cd.ConnectionName = CONNAME.encode()
    cd.ChannelType = CMQC.MQCHT_CLNTCONN
    cd.TransportType = CMQC.MQXPT_TCP

    # TLS config (uses the key repository as truststore)
    sco = pymqi.SCO()
    sco.KeyRepository = KEY_REPO.encode()
    cd.SSLCipherSpec = CIPHERSPEC.encode()

    # Security parms (user/password) -> MQ validates via LDAP if configured
    csp = pymqi.CSP()
    csp.AuthenticationType = CMQC.MQCSP_AUTH_USER_ID_AND_PWD
    csp.UserId = USER.encode()
    csp.Password = PASSWORD.encode()

    # Connection options
    cno = pymqi.CNO()
    cno.Options = CMQC.MQCNO_NONE
    cno.SecurityParms = csp
    cno.SSLConfig = sco

    qmgr = pymqi.QueueManager(None)
    qmgr.connect_with_options(QMGR_NAME, cd, cno)
    return qmgr

def main():
    qmgr = connect()
    print("Connected OK")

    q = pymqi.Queue(qmgr, "DEV.QUEUE.1")

    # PUT
    msg = b"hello from python"
    q.put(msg)
    print("Put message")

    # GET
    md = pymqi.MD()
    gmo = pymqi.GMO()
    gmo.Options = CMQC.MQGMO_WAIT | CMQC.MQGMO_FAIL_IF_QUIESCING
    gmo.WaitInterval = 5000  # ms

    data = q.get(None, md, gmo)
    print("Got message:", data)

    q.close()
    qmgr.disconnect()
    print("Disconnected")

if __name__ == "__main__":
    main()



